name: Deploy

on:
  # Allow to run manually
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials (for Terraform S3 backend)
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_DEFAULT_REGION:
          AWS_REGION:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_SESSION_TOKEN:
        with:
          aws-access-key-id: ${{ secrets.DO_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DO_S3_SECRET_KEY }}
          aws-region: us-east-1 # doesn't matter for DigitalOcean, required by AWS GH action

      - name: Test S3 access
        run: aws s3 ls --endpoint=https://managed-prototypes.ams3.digitaloceanspaces.com
